package com.synauson.jsyn.participant;

import com.synauson.jsyn.WebRtcStats;
import com.synauson.jsyn.internal.NativeBridge;
import java.util.Objects;

/**
 * Handle to a WebRTC participant returned by
 * {@link com.synauson.jsyn.participant.Conference#addWebRtcParticipant}.
 *
 * <p>Carries the participant ID and the SDP answer to relay back to the browser. Use
 * {@link Conference#streamWebRtcIceCandidates} to receive trickle-ICE candidates from
 * the GStreamer webrtcbin and relay them to the browser; call
 * {@link #addIceCandidate(String, int)} to push remote candidates back into the
 * pipeline.
 *
 * @since 0.1.0
 */
public final class WebRtcParticipantHandle {
    private final long runtimeHandle;
    private final String conferenceId;
    private final String participantId;
    private final String sdpAnswer;

    /**
     * Construct a WebRTC participant handle. Invoked by
     * {@link Conference#addWebRtcParticipant} after the native call returns; rarely
     * constructed from application code.
     *
     * @param runtimeHandle opaque runtime handle from {@code NativeBridge.initRuntime}
     * @param conferenceId  conference identifier; non-null
     * @param participantId participant identifier; non-null
     * @param sdpAnswer     SDP answer generated by the GStreamer webrtcbin; non-null
     * @throws NullPointerException if any reference argument is null
     */
    public WebRtcParticipantHandle(long runtimeHandle, String conferenceId,
                                    String participantId, String sdpAnswer) {
        this.runtimeHandle = runtimeHandle;
        this.conferenceId = Objects.requireNonNull(conferenceId, "conferenceId");
        this.participantId = Objects.requireNonNull(participantId, "participantId");
        this.sdpAnswer = Objects.requireNonNull(sdpAnswer, "sdpAnswer");
    }

    /**
     * Returns the participant's assigned identifier.
     *
     * @return the participant ID
     */
    public String id() { return participantId; }

    /**
     * Returns the SDP answer generated by the GStreamer webrtcbin. Relay this to the
     * browser to complete the SDP exchange.
     *
     * @return the SDP answer string
     */
    public String sdpAnswer() { return sdpAnswer; }

    /**
     * Add a trickle-ICE candidate received from the remote browser.
     *
     * @param candidate     SDP candidate string (e.g. {@code "candidate:..."})
     * @param sdpMLineIndex SDP m-line index the candidate applies to; non-negative
     * @throws com.synauson.jsyn.exception.NotFoundException if the participant no longer exists
     * @throws com.synauson.jsyn.exception.InvalidArgumentException if the candidate string is malformed
     */
    public void addIceCandidate(String candidate, int sdpMLineIndex) {
        NativeBridge.addWebRtcIceCandidate(runtimeHandle, conferenceId, participantId,
                                            candidate, (long) sdpMLineIndex);
    }

    /**
     * Retrieve per-participant WebRTC quality statistics.
     *
     * @return a fresh stats snapshot
     * @throws com.synauson.jsyn.exception.NotFoundException if the participant no longer exists
     */
    public WebRtcStats stats() {
        String json = NativeBridge.getWebRtcStats(runtimeHandle, conferenceId, participantId);
        return WebRtcStats.fromJson(json);
    }
}
